### ISSUE TITLE
Multi-core virtual machine

### ISSUE THREAD

**Issue by podhrmic** [au-ts/camkes_to_sel4cp_guide#2]
Hello!

I am wondering if it is possible to create a VM that uses multiple cores. The examples in the guide are very comprehensive, but one can imagine a situation where a multi-core VM might be necessary. Do you anticipate having this functionality in the core platform?

**Comment by abrandnewusername** [comment]
We are indeed planning to add support for configuring/handling multiple vCPUs to the seL4CP VMM. I will update the guide after this is done.

**Comment by Ivan-Velickovic** [comment]
It's currently mentioned in the guide: "seL4CP VMM doesn't currently handle multiple vCPUs, but the feature will be added in the future" and it's in the VMM roadmap https://github.com/au-ts/sel4cp_vmm#roadmap.

We should also mention it in the guide section on future work.

**Comment by Ivan-Velickovic** [comment]
I've updated the guide now to mention the intention of multi-VCPU/multi-core virtual machines in the future work section.
